### ISSUE TITLE
Documenation for using saved Topology

### ISSUE THREAD

**Issue by indiejames** [sakex/neat-gru-rust#19]
I have run the XOR example successfully, and I have been able to modify the code to work with training for my own simple game, but I have no idea how to use the output file. I see that it comes from the `impl` for `Display` for `Topology`, but knowing very little about NEAT I have no idea how to translate that into an executable (inferencing) NN. Ideally I would like to be able to parse the output file in a way that I could then implement the resulting NN in a language other than rust, e.g., C++. 

Can you provide documentation (or links to documentation) of the output format that would allow this? Ideally (for me at least) your could add the ability to output some common format like NNEF (https://en.wikipedia.org/wiki/Neural_Network_Exchange_Format) so that networks trained with your code could be used by other inference engines, but that's a big ask. In the meantime I'm happy to try to educate myself by reading documentation, but I don't know where to start.

**Comment by sakex** [comment]
Thanks for the feedback. I made it a JSON for convenience but it is indeed not ideal to support alternative environments. The issue we have is that the NEAT networks are not fully connected and layers basically don't exist.They are sparse networks, if you point me to the NNEF documentation to implement such networks, I'll gladly do it for you over the weekend. Otherwise, if your goal is simply to use the network in C++, i can easily show you how to do that over discord this weekend.Cheers,ASOn Feb 22, 2023 23:17, James Norton ***@***.***> wrote:
I have run the XOR example successfully, and I have been able to modify the code to work with training for my own simple game, but I have no idea how to use the output file. I see that it comes from the impl for Display for Topology, but knowing very little about NEAT I have no idea how to translate that into an executable (inferencing) NN. Ideally I would like to be able to parse the output file in a way that I could then implement the resulting NN in a language other than rust, e.g., C++.
Can you provide documentation (or links to documentation) of the output format that would allow this? Ideally (for me at least) your could add the ability to output some common format like NNEF (https://en.wikipedia.org/wiki/Neural_Network_Exchange_Format) so that networks trained with your code could be used by other inference engines, but that's a big ask. In the meantime I'm happy to try to educate myself by reading documentation, but I don't know where to start.

**Comment by indiejames** [comment]
Thanks for responding so quickly. I skimmed through the NNEF specification https://registry.khronos.org/NNEF/specs/1.0/nnef-1.0.pdf and I see an example on page 85 of a fragment that implements a GRU, but I don't see specific mention of sparse networks. Presumably you could either use tensors of shape (1,1) to represent single connections between nodes or just use tensors with zeros for the weights between unconnected nodes, but neither approach seems optimal. There is also the ONNX format https://onnx.ai/onnx/intro/concepts.html#shape-and-type-inference, but as that is not a text based file format it might be harder to implement.

I think I would be happy with a simple description of what the various elements in the output format mean. For instance, the XOR output has this (abbreviated)

```
{
  "biases": [
    {
      "neuron": [
        2,
        0
      ],
      "bias": {
        "bias_input": 0.13091288619825764,
        "bias_update": 0.25254100646824457,
        "bias_reset": -0.05194399167819455
      }
    },
    {
      "neuron": [
        0,
        2
      ],
      "bias": {
        "bias_input": 0.1452746363093856,
        "bias_update": 0.1614108314746565,
        "bias_reset": -0.08978148437610578
      }
    },
...
],
  "genes": [
    {
      "connection_type": 1,
      "disabled": false,
      "input": [
        2,
        0
      ],
      "input_weight": 0.811168810306101,
      "memory_weight": 1.0784347229859532,
      "output": [
        3,
        0
      ],
      "reset_input_weight": 0.8501673239653501,
      "reset_memory_weight": 1.0406771573670428,
      "update_input_weight": 1.1662245555460302,
      "update_memory_weight": 0.6072342161932146,
      "ev_number": 110.0
    },
...
 ]
}
```
I'm guessing the "neuron" entries under "biases" represent the neurons in the network and their associated biases (although I don't know how the biases other than the "input" biases are used). Similarly I'm assuming [2, 0] notation after "neuron" is some sort of identifier, but I'm not sure why there are two numbers. 

I'm also guessing that the "genes" are the connections between nodes, with the two numbers for input and output corresponding to the two numbers used as node identifiers. I don't know how the weights beyond "input_weight" are used - assuming it's related to a GRU. Ditto about "ev_number".

A simple diagram of the network described by the XOR output file would also be very helpful.

Most of my questions are probably due to my lack of knowledge about GRU, so I apologize for that. Thanks again for your help.

**Comment by sakex** [comment]
Hey, after your mail, I started toying a bit with the idea of making C bindings. Can you have a look at the c_bindings branch (https://github.com/sakex/neat-gru-rust/commit/525fd522cdc4cb058ba3f880530e865cab80f3ed).I made two bash scripts so you can try building as a shared library, it will install in /usr/local and and copy the headers and test it from C++ code.- bootstrap.sh installs the dynamic library- test_c_bindings.sh runs the tests in neat_gru_lib/test.ccI plan on making a NeuralNetwork<T> c++ class laterOn Feb 23, 2023 03:06, James Norton ***@***.***> wrote:
Thanks for responding so quickly. I skimmed through the NNEF specification https://registry.khronos.org/NNEF/specs/1.0/nnef-1.0.pdf and I see an example on page 85 of a fragment that implements a GRU, but I don't see specific mention of sparse networks. Presumably you could either use tensors of shape (1,1) to represent single connections between nodes or just use tensors with zeros for the weights between unconnected nodes, but neither approach seems optimal. There is also the ONNX format https://onnx.ai/onnx/intro/concepts.html#shape-and-type-inference, but as that is not a text based file format it might be harder to implement.
I think I would be happy with a simple description of what the various elements in the output format mean. For instance, the XOR output has this (abbreviated)
{
  "biases": [
    {
      "neuron": [
        2,
        0
      ],
      "bias": {
        "bias_input": 0.13091288619825764,
        "bias_update": 0.25254100646824457,
        "bias_reset": -0.05194399167819455
      }
    },
    {
      "neuron": [
        0,
        2
      ],
      "bias": {
        "bias_input": 0.1452746363093856,
        "bias_update": 0.1614108314746565,
        "bias_reset": -0.08978148437610578
      }
    },
...
],
  "genes": [
    {
      "connection_type": 1,
      "disabled": false,
      "input": [
        2,
        0
      ],
      "input_weight": 0.811168810306101,
      "memory_weight": 1.0784347229859532,
      "output": [
        3,
        0
      ],
      "reset_input_weight": 0.8501673239653501,
      "reset_memory_weight": 1.0406771573670428,
      "update_input_weight": 1.1662245555460302,
      "update_memory_weight": 0.6072342161932146,
      "ev_number": 110.0
    },
...
 ]
}

I'm guessing the "neuron" entries under "biases" represent the neurons in the network and their associated biases (although I don't know how the biases other than the "input" biases are used). Similarly I'm assuming [2, 0] notation after "neuron" is some sort of identifier, but I'm not sure why there are two numbers.
I'm also guessing that the "genes" are the connections between nodes, with the two numbers for input and output corresponding to the two numbers used as node identifiers. I don't know how the weights beyond "input_weight" are used - assuming it's related to a GRU. Ditto about "ev_number".
A simple diagram of the network described by the XOR output file would also be very helpful.
Most of my questions are probably due to my lack of knowledge about GRU, so I apologize for that. Thanks again for your help.

**Comment by indiejames** [comment]
I'll try to take a look this weekend, thanks.
