### ISSUE TITLE
Question regarding license

### ISSUE THREAD

**Issue by indiejames** [sakex/neat-gru-rust#21]
First of all, thanks for making this. I have been able to use it to train a network that works with the game I am developing and thanks to the recent C/C++ bindings I have been able to build a static iOS library that should be usable in-game.
After having done this I realized that you are using the GPL-3.0 license (unlike your previous NEAT-GRU C++ project, which uses the MIT license). I support your right to use whatever license you want - it's your work, but the GPL-3.0 license is not compatible with the Apple App Store, my target audience. 

Was there a particular reason for moving to GPL-3.0, and, if not, would you consider a less restrictive license?

Either way, thanks for the great work.

**Comment by sakex** [comment]
Hey, thanks for pointing this out. I the time we started the project, we were using the algorithm as part of a larger private project that was itself meant to become GPL3. In the end, we are not going to open source the project because of multiple secrets we'd rather keep (it's an automated trading strategy.)

Anyway, if you want to make it MIT, feel free to send me a PR, I will approve it.

**Comment by indiejames** [comment]
Thank you - done. https://github.com/sakex/neat-gru-rust/pull/22

**Comment by sakex** [comment]
Merged :) Please send a link to your game once it's ready !
